version: '3.8'

services:
  # NestJS Application
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecomize_backend
    ports:
      - "8888:8888"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
      - /usr/src/app/src/generated/master
      - /usr/src/app/src/generated/tenant
    environment:
      - PORT=8888
      - DATABASE_URL=postgresql://postgres:postgres@postgres_master:5432/master_db?schema=public
      - MASTER_DATABASE_URL=postgresql://postgres:postgres@postgres_master:5432/master_db?schema=public
      - MASTER_DIRECT_URL=postgresql://postgres:postgres@postgres_master:5432/master_db?schema=public
      - DIRECT_URL=postgresql://postgres:postgres@postgres_master:5432/master_db?schema=public
      - TENANT_DATABASE_TEMPLATE_URL=postgresql://postgres:postgres@postgres_tenant:5432/tenant_template_db?schema=public
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=super_secret_key_for_testing
      - APP_URL=http://localhost:8888
    depends_on:
      - postgres_master
      - postgres_tenant
      - redis
    networks:
      - ecomize_network

  # Master DB
  postgres_master:
    image: postgres:15-alpine
    container_name: ecomize_postgres_master
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=master_db
    ports:
      - "5431:5432"
    volumes:
      - ecomize_master_data:/var/lib/postgresql/data
    networks:
      - ecomize_network

  # Tenant Template DB (can be used to provision new tenant databases locally)
  postgres_tenant:
    image: postgres:15-alpine
    container_name: ecomize_postgres_tenant
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tenant_template_db
    ports:
      - "5432:5432"
    volumes:
      - ecomize_tenant_data:/var/lib/postgresql/data
    networks:
      - ecomize_network

  # Redis for Queue and OTP caching
  redis:
    image: redis:7-alpine
    container_name: ecomize_redis
    ports:
      - "6379:6379"
    volumes:
      - ecomize_redis_data:/data
    networks:
      - ecomize_network

networks:
  ecomize_network:
    driver: bridge

volumes:
  ecomize_master_data:
  ecomize_tenant_data:
  ecomize_redis_data:
